language: csharp
mono: none
dotnet: 2.1

install:
    - dotnet restore
    
script:
    - dotnet build
    - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - dotnet tool install --global coveralls.net --version 1.0.0
    - export PATH="$PATH:/home/travis/.dotnet/tools"
    - csmacnz.Coveralls --opencover -i Mklinker.Tests/coverage.opencover.xml --useRelativePaths --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName travis-ci
    - dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.3
    - reportgenerator "-reports:Mklinker.Tests/coverage.opencover.xml" "-targetdir:gh-pages/CoverageReport" -reporttypes:Html

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: gh-pages
    target_branch: gh-pages