language: csharp
mono: none
dotnet: 3.1

install:
    - dotnet restore
    
script:
    - dotnet build
    - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - export PATH="$PATH:/home/travis/.dotnet/tools"
    - dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.3
    - reportgenerator "-reports:Mklinker.Tests/coverage.opencover.xml" "-targetdir:gh-pages/CoverageReport" -reporttypes:Html

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: gh-pages
    target_branch: gh-pages