language: csharp
solution: Mklinker.sln

install:
  - nuget restore Mklinker.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Mklinker.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Mklinker/bin/Release/Mklinker.exe