language: csharp
mono: none
dotnet: 3.0
dotnet: 2.1

install:
    - dotnet restore
    
script:
    - dotnet build
    - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - dotnet tool install --global coveralls.net --version 1.0.0
    - export PATH="$PATH:/home/travis/.dotnet/tools"
    - export COVERALLS_REPO_TOKEN=iF0Z7FbaDPzUmhPb6SWLbn4bJAlUyvPON
    - csmacnz.Coveralls --opencover -i Mklinker.Tests/coverage.opencover.xml --useRelativePaths --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName travis-ci